experiment = 'experiments_c'
path       = ""

["simulation"]
"stop_time"     = "48hours"
"Δt"            = "1second"
"max_Δt"        = "10minutes"
"Δt_output_fld" = "1minutes"

["grid"]
# GRID DIMENSIONS (set to 1 if slice along this dim
Nx = 64
Ny = 1
Nz = 128
# GRID EXTENT
Lx = "100meters"
Ly = "0meters"
Lz = "100meters"
# depth of seawater parcel
"z₀" = "0meters"
# stretching of z-level
# refinement controls spacing near surface (higher means finer spaced) (1.2)
refinement = 1.2
# stretching controls rate of stretching at bottom (12)
stretching = 12

["far-field values"]
"V∞" = 0.02     # far field velocity                 m s⁻¹
"N²" = 1e-5     # far field buoyancy gradient        s⁻¹

["physical parameters"]
"f₀" = -1.0e-4  # Coriolis parameter                 rad s⁻¹
"κ"  = 1.0e-5   # molecular diffusivity              m² s⁻¹
"ν"  = 1.0e-4   # molecular viscosity                m² s⁻¹
"cᴰ" = 3.0e-3   # drag coefficient
