experiment = 'experiments_c'
path       = ""

["simulation"]
"stop_time"     = "50 hours"
"Δt"            = "1 second"
"max_Δt"        = "1 minute"
"Δt_output_fld" = "5 minute"

["grid"]
# GRID DIMENSIONS
Nx = 25
Nz = 50
# GRID EXTENT
Lx = "10 meters"
Lz = "20 meters"
# depth of seawater parcel
"z₀" = "0 meters"

["far-field values"]
"V∞" = 0.014    # far field velocity                 m s⁻¹
"N²" = 1e-5     # far field buoyancy gradient        s⁻¹

["physical parameters"]
"κ"  = 1.0e-4   # molecular diffusivity              m² s⁻¹
"ν"  = 1.0e-4   # molecular viscosity                m² s⁻¹
"zᵣ" = 0.1      # roughness length                   m
"κᵣ" = 0.4      # von Karman constant
#"cᴰ" = 2.5e-3   # drag coefficient
