experiment = 'experiments_c'
path       = ""

["simulation"]
"stop_time"     = "50hours"
"Δt"            = "1second"
"max_Δt"        = "1minute"
"Δt_output_fld" = "5minutes"

["grid"]
# GRID DIMENSIONS (set to 1 if slice along this dim
Nx = 25
Ny = 1
Nz = 50
# GRID EXTENT
Lx = "10meters"
Ly = "0meters"
Lz = "20meters"
# depth of seawater parcel
"z₀" = "0meters"

["far-field values"]
"V∞" = 0.014    # far field velocity                 m s⁻¹
"N²" = 1e-5     # far field buoyancy gradient        s⁻¹

["physical parameters"]
"κ"  = 1.0e-4   # molecular diffusivity              m² s⁻¹
"ν"  = 1.0e-4   # molecular viscosity                m² s⁻¹
"zᵣ" = 0.1      # roughness length                   m
"κᵣ" = 0.4      # von Karman constant
#"cᴰ" = 2.5e-3   # drag coefficient
