experiment = 'experiments_c'
path       = ""

["simulation"]
"stop_time"     = "48hours"
"Δt"            = "1second"
"max_Δt"        = "20minutes"
"Δt_output_fld" = "20minutes"

["grid"]
# GRID DIMENSIONS (set to 1 if slice along this dim
Nx = 25
Ny = 1
Nz = 50
# GRID EXTENT
Lx = "25meters"
Ly = "0meters"
Lz = "50meters"
# depth of seawater parcel
"z₀" = "0meters"
# stretching of z-level
# refinement controls spacing near surface (higher means finer spaced) (1.2)
refinement = 1.2
# stretching controls rate of stretching at bottom (12)
stretching = 12

["far-field values"]
"V∞" = 0.014    # far field velocity                 m s⁻¹
"N²" = 1e-5     # far field buoyancy gradient        s⁻¹

["physical parameters"]
"κ"  = 1.0e-4   # molecular diffusivity              m² s⁻¹
"ν"  = 1.0e-4   # molecular viscosity                m² s⁻¹
"zᵣ" = 0.1      # roughness length                   m
"κᵣ" = 0.4      # von Karman constant
#"cᴰ" = 2.5e-3   # drag coefficient
