experiment = 'experiments_0'
path       = ""

["simulation"]
"stop_time"        = "100 seconds"
"Δt"               = "1 second"
"max_Δt"           = "10 minutes"

["grid"]
# GRID DIMENSIONS
Nx = 1
Ny = 1
Nz = 1
# GRID EXTENT
Lx = "1 meter"
Ly = "1 meter"
Lz = "1 meter"
