experiment = 'test_setup'
path       = ""

["simulation"]
"stop_time"        = "100seconds"
"Δt"               = "1second"
"max_Δt"           = "10minutes"

["grid"]
# GRID DIMENSIONS
Nx = 1
Ny = 1
Nz = 1
# GRID EXTENT
Lx = "1meter"
Ly = "1meter"
Lz = "1meter"
